### ISSUE TITLE
Continue Game contains saved games unable to play

### ISSUE THREAD

**Issue by dcshoecomp** [SecUSo/privacy-friendly-minesweeper#5] opened 2019-03-29 13:24 UTC
If you start a new game, and exit, then attempt to continue the game you are unable to actually continue the game. One click on the continued game makes all the tiles faded out and only the mark/unmark button works.

**Comment by petermayer** [comment] 2019-04-09 16:01
Hi @dcshoecomp, I will close this issue, since it is a duplicate of #4

**Closed by petermayer** 2019-04-09 16:02 UTC
